---
- name: Modify standard ssh port in sshd_config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ ssh_port }}"
  notify: Restart sshd

- name: Prevent root login
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart sshd

- name: Add id_rsa.pub to sudo user
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ lookup('file', public_key_path) }}"
    exclusive: yes

- name: Prevent password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart sshd

