---
- name: Modify standard ssh port in sshd_config
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ ssh_port }}"
  notify: Restart sshd

- name: Prevent root login
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart sshd

- name: Prevent password authentication
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart sshd

